configs:
  gnb_config.yml:
    file: ../configs/gnb_config.yml

services:
    gnb:
        networks:
            sdr_net:
                ipv4_address: 192.168.20.100
        command: /bin/bash

networks:
    sdr_net:
        driver: macvlan
        driver_opts:
            parent: enx00e04c681f5a
        ipam:
            config:
                - subnet:  192.168.20.0/24
                  gateway: 192.168.20.254


        
