name: Makefile CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install flake8 from requirements.txt
        run: make setup
      - name: run flake8 linter
        run: flake8  ./

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (and run) project
        run: make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependancies
        run: make setup
      - uses: actions/checkout@v4
      - name: Test project
        run: make test
