name: Makefile CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (and run) project
        run: make
      - name: run make
        run: |
          docker save $(docker images -q) > docker-images.tar
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_id }}
          path: docker-images.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependancies
        run: make setup
      - uses: actions/checkout@v4
      - name: Test project
        run: make test
